### PR TITLE
Backend add conversation model #2

### PR DESCRIPTION
**Pull request by leiwang758**
### What this PR does (required):
- Add conversation and message model

### Screenshots / Videos (required):
- image

### Any information needed to test this feature (required):
- In the command line, run node and connect to mongoose to create an empty conversion record
```javascript
const mongoose = require("mongoose")
mongoose.connect(url)
const conv = require("./models/conversation")
conv.create({users:[], messages:[]})
```

### Any issues with the current functionality (optional):
- List any problems where you were not able to complete all tasks on ticket
- List any problems this PR may cause for the project or other active PRs
- Post a screenshot/video of the problem, along with detailed console outputs where applicable

### CODE REVIEW

**Review by bonnieli — COMMENTED** [review]
This looks like just the Message model, and based off of your description, should we be expecting a file called Conversation.js as well?

**Comment by leiwang758** [comment]
> This looks like just the Message model, and based off of your description, should we be expecting a file called Conversation.js as well?

Conversation.js was added in the previous commits, I made multiple commits because I realized some errors and for some reason, it only shows the latest commit.

**Comment by sina-jamshidi** [comment]
> > This looks like just the Message model, and based off of your description, should we be expecting a file called Conversation.js as well?
> 
> Conversation.js was added in the previous commits, I made multiple commits because I realized some errors and for some reason, it only shows the latest commit.

Accidentally edited your comment instead of replying lol. When you click the commits you can see the diff and it looks like you accidentally removed Conversation.js. Please re-add both to the branch and push the changes again

**Comment by leiwang758** [comment]
> > > This looks like just the Message model, and based off of your description, should we be expecting a file called Conversation.js as well?
> > 
> > 
> > Conversation.js was added in the previous commits, I made multiple commits because I realized some errors and for some reason, it only shows the latest commit.
> 
> Accidentally edited your comment instead of replying lol. When you click the commits you can see the diff and it looks like you accidentally removed Conversation.js. Please re-add both to the branch and push the changes again

Yeah you are right, I just added both changes

**Pull request merged**
