### PR TITLE
integrated invitation tab into ChatSideBanner component

### PR DESCRIPTION
**Pull request by TedGu**
### What this PR does (required):
-added a `<Tabs>` includes `ChatsTab`, `ContactsTab` and `InvitationsTab` named  `ChatsContactsInvitationsTabs`
-replaced 'ContactsTab` in `ChatSideBanner` with `ChatsContactsInvitationsTabs`
-updated `.eslintrc` with new rule to `{} type`

### Screenshots / Videos (required):
image
image
image

### Any information needed to test this feature (required):
- The component `ChatsContactsInvitationsTabs` is a part of the component `ChatSideBanner`

### CODE REVIEW

**Review by dproc96 — CHANGES_REQUESTED** [review]
Screen Shot 2021-06-04 at 8 35 38 AM
Screen Shot 2021-06-04 at 8 35 48 AM
Because of the spacing, these tabs can't actually be used. Can you fix this so that on the average screen, all of the tabs can be easily seen?

**Comment by TedGu** [comment]
with new style:
image

**Comment by dproc96** [comment]
Screen Shot 2021-06-07 at 8 19 12 AM
This branch is failing to compile now

**Comment by TedGu** [comment]
`"@typescript-eslint/ban-types": [
      "error",
      {
        "extendDefaults": true,
        "types": {
          "{}": false
        }
      }
    ]`
should be added to .eslintrc rules section.
like this:
  "rules": {
    // suppress errors for missing 'import React' in files
    "react/react-in-jsx-scope": "off",
    "react/prop-types": "off",
    "prettier/prettier": [
      "error",
      {
        "endOfLine": "auto"
      }
    ],
    "@typescript-eslint/ban-types": [
      "error",
      {
        "extendDefaults": true,
        "types": {
          "{}": false
        }
      }
    ]
  }

My branch has been changed into this, but GitHub did not change.

**Pull request merged**
