### PR TITLE
Invitation tab (next to contacts) #19

### PR DESCRIPTION
**Pull request by TedGu**
### What this PR does (required):
- Invitation tab

### Screenshots / Videos (required):
image

### Any information needed to test this feature (required):
- a list of the pending invitations for the logged-in user
- the slider after each invitation can be set to -1(Reject) or 1(Approve)

### CODE REVIEW

**Review by sina-jamshidi — COMMENTED** [review]
From a UI perspective I don't think the slider is very easy to use. Two buttons ("Reject" or "Approve") will be a better way to go

**Comment by dproc96** [comment]
It doesn't look like these components are actually being used anywhere in the app, can you put them in so that we can test it? Also just a note there is a lot of additional code coming from other PRs in here, please be aware of this in the future when working on multiple tasks

**Comment by TedGu** [comment]
Like ContactsTab
new UI like this:
image

It can be used under `<TabPanel>` and with `<Tab label="Invitations">` next to the ContactsTab if there is any pending invitations.

**Comment by dproc96** [comment]
> Like ContactsTab
> new UI like this:
> image
> 
> It can be used under `<TabPanel>` and with `<Tab label="Invitations">` next to the ContactsTab if there are any pending invitations.

Just to clarify, neither of these Tabs are showing up in the UI. I'm not sure if you pushed the change that makes them visible.

**Pull request merged**
